services:
  meow:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.meow
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
      # TCP mode by default for local development
      - USE_VSOCK=${USE_VSOCK:-false}
      - ENCLAVE_ADDRESS=${ENCLAVE_ADDRESS:-meow-enclave:5005}
      - ENCLAVE_CID=${ENCLAVE_CID:-16}
      - VSOCK_PORT=${VSOCK_PORT:-5005}
    ports:
      - "8080:8080"
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      - meow-enclave

  meow-enclave:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.enclave
    env_file:
      - .env
    environment:
      - RUST_LOG=info
      # TCP mode for Docker, vsock mode for Nitro
      - USE_VSOCK=${USE_VSOCK:-false}
      - TCP_ADDRESS=0.0.0.0:5005
      - VSOCK_CID=${VSOCK_CID:-16}
      - VSOCK_PORT=${VSOCK_PORT:-5005}
    ports:
      - "5005:5005"
    restart: unless-stopped
    command: ["./enclave"]

  # Development enclave with debug logging
  meow-enclave-debug:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.enclave
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
      - USE_VSOCK=false
      - TCP_ADDRESS=0.0.0.0:5005
    ports:
      - "5005:5005"
    restart: unless-stopped
    command: ["./enclave"]
    profiles:
      - debug

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - RUST_LOG=debug
    volumes:
      - .:/app
    depends_on:
      - meow
    # No default command - we'll specify it when running
