services:
  meow:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.meow
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
    ports:
      - "8080:8080"
    restart: unless-stopped
    stop_grace_period: 30s

  meow-enclave:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.enclave
    env_file:
      - .env
    environment:
      - ENCLAVE_MODE=enclave
      - RUST_LOG=info
    ports:
      - "8081:8080"
    restart: unless-stopped
    command: ["./enclave"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - RUST_LOG=debug
    volumes:
      - .:/app
    depends_on:
      - meow
    # No default command - we'll specify it when running
