services:
  # Local development service
  meow:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
    volumes:
      - ./meow:/usr/src/purrbot/meow
      - ./9sdk:/usr/src/purrbot/9sdk
      - ./9sdk-enclave:/usr/src/purrbot/9sdk-enclave
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: sh -c "echo 'Environment variables:' && env && echo 'Starting meow...' && ./meow"

  # Enclave service
  meow-enclave:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - ENCLAVE_MODE=enclave
      - RUST_LOG=info
    ports:
      - "8081:8080"  # Different port for enclave service
    restart: unless-stopped
    command: sh -c "echo 'Environment variables:' && env && echo 'Starting enclave...' && ./enclave"
    # Add any enclave-specific configurations here
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  # Optional: Add a development database or other services as needed
  # db:
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_USER=meow
  #     - POSTGRES_PASSWORD=meow
  #     - POSTGRES_DB=meow
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: 