services:
  meow:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.meow
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
    ports:
      - "8080:8080"
    restart: unless-stopped
    # Default command (./meow) is in Dockerfile, so no override needed here.

  meow-enclave:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile.enclave
    env_file:
      - .env
    environment:
      - ENCLAVE_MODE=enclave
      - RUST_LOG=info
    ports:
      - "8081:8080"  # Expose to a different host port for testing
    restart: unless-stopped
    command: ["./enclave"]
